# Provide a set of configuration files (with a default) for the plugin.
# An example might look like the following:
# config:
#   default: "config-none"
#   files:
#   - name: "config-none"
#     contents: |-
#       version: v1
#       flags:
#         migStrategy: none
#   - name: "config-mixed"
#     contents: |-
#       version: v1
#       flags:
#         migStrategy: mixed
config:
  default: null
  files: []

disableHealthchecks: true
legacyDaemonsetAPI: null
compatWithCPUManager: null
migStrategy: null
failOnInitError: null
deviceListStrategy: null
deviceIDStrategy: null
nvidiaDriverRoot: null

nameOverride: ""
fullnameOverride: ""
selectorLabelsOverride: {}

namespace: kube-system

imagePullSecrets: []
image:
  repository: nvcr.io/nvidia/k8s-device-plugin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

updateStrategy:
  type: RollingUpdate

podSecurityContext: {}
securityContext: {}

resources: {}
nodeSelector: {}
affinity: {}
tolerations:
  # This toleration is deprecated. Kept here for backward compatibility
  # See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
  - key: CriticalAddonsOnly
    operator: Exists
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

runtimeClassName: null
